### ISSUE TITLE
can we remove the cell toolbars?

### ISSUE THREAD

**Issue by mikofski** [mikofski/PVSC48-Python-Tutorial#10]
Hi @shirubana , would it be okay to hide the cell toolbars that say "slideshow"? I think they're a distraction during the tutorial, and for anyone who wants to generate a slideshow from the tutorial, they would probably do it on their personal machines using their own personal clone. thanks!

**Comment by shirubana** [comment]
For the release version they are going to use yes, we can toggle them off, but while were working with them that helps us cluster the content in short chunks, we can set them properly and then hide them -- I still think we can try using the slide mode which allows you to run code now to present the content
