### ISSUE TITLE
what is "global_mean_surface_temp" in tutorial-1 going deeper refer to?

### ISSUE THREAD

**Issue by mikofski** [mikofski/PVSC48-Python-Tutorial#16]
in tutorial 1 it says:

https://github.com/mikofski/PVSC48-Python-Tutorial/blob/f73c5cbcbba320e45f2d9ec4df74ecd6ee4f32e9/Tutorial%200%20-%20Overview.ipynb#L230

what notebook is this referring to? I checked in pvlib, and I can't find this notebook. Was it one of the pvsc48 tutorial notebooks that got renamed? Am I just not seeing it? Can we make a link?

**Comment by mikofski** [comment]
Is it this? http://gallery.pangeo.io/repos/pangeo-gallery/cmip6/global_mean_surface_temp.html

**Comment by mikofski** [comment]
@shirubana or @kanderso-nrel know anything about this? I want to close and resolve all issues so we can start using the upstream repo. https://github.com/PVSC-Python-Tutorials/PVSC48-Python-Tutorial
thanks!

**Comment by kanderso-nrel** [comment]
I don't know anything about `global_mean_surface_temp.ipynb` :(

**Comment by mikofski** [comment]
@shirubana okay to change this? I think it was a placeholder maybe? you can blame the commit and see it was added 2020-11-25
![image](https://user-images.githubusercontent.com/1385621/118870246-2d09f100-b89b-11eb-9b4d-2a135a92ced6.png)

**Comment by mikofski** [comment]
fixed in https://github.com/PVSC-Python-Tutorials/PVSC48-Python-Tutorial/commit/ad7916ee50df53889644d613f88c8d2e1e4009c6
